#!/usr/bin/python
def options(opt):
  pass

def configure(conf):
  pass

def build(bld):

  # name of the target
  targetName='App.PathTracker'

  # the list of source files that need to be built
  appSrc = bld.path.ant_glob('*.cpp')

  # external libraries

  # build the library
  bld.program(source=appSrc,
              target=targetName,
              install_path=bld.env.BIN_DIR,
              use=['commonIncludes', 
                   'PathTracker', 
                   'TRMC',
                   'boost_serialization',
                   'boost_thread',
                   'boost_log'
                   'boost_system'],
              includes=bld.env.INCLUDES)
