% [states,...] = predTrajModel(stateInit,controls,dt,...)
% trainModel(inputStruct)
% testModel(inputStruct)
% statesFinal = predictModelDynDataset(dynDataset,...)
% [...] = dynDatasetDynToModelDataset(dynDataset,...)
