#!/usr/bin/python

def configure(conf):
  print("Configuring apps")
  conf.recurse('App.PathTracker')
#  conf.recurse('SimulatorApp')
  
def build(bld):
  print("Building apps")
  bld.recurse(['App.PathTracker'])


